log_level: debug

metrics:
  enabled: true
  addr: ":9090"

notification:
  webhook_url: "" # Add your Discord/Slack webhook URL here

traps:
  http_infinite:
    enabled: true
    addr: ":8080"
    server_name: "nginx"
  json_infinite:
    enabled: true
    addr: ":8081"
    server_name: "api-gateway"
  spider_trap:
    enabled: true
    addr: ":8082"
    server_name: "apache"
  gzip_infinite:
    enabled: true
    addr: ":8083"
    server_name: "nginx"
  login_trap:
    enabled: true
    addr: ":8084"
    server_name: "admin-panel"
