log_level: debug

metrics:
  enabled: true
  addr: ":9090"

traps:
  http_infinite:
    enabled: true
    addr: ":8080"
    server_name: "nginx"
  json_infinite:
    enabled: true
    addr: ":8081"
    server_name: "api-gateway"
